#!/bin/bash

# Arguments: filename, EPSG code

FILENAME=$1
BNAME=${FILENAME%.las}
SRS=EPSG:$2

# path to this script
SPATH=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

echo "\nGenerate DTM (using ground points)"
time pdal pipeline -i $SPATH/dtm.xml --writers.p2g.filename=${BNAME}_DTM --readers.las.filename=$FILENAME --writers.p2g.spatialreference=$SRS

echo "\nGenerate DSM (using all points)"
time pdal pipeline -i $SPATH/dsm.xml --writers.p2g.filename=${BNAME}_DSM --readers.las.filename=$FILENAME --writers.p2g.spatialreference=$SRS

echo "\nGenerate CHM"
time $SPATH/make_chm.py ${BNAME}_DSM.max.tif ${BNAME}_DTM.idw.tif ${BNAME}_CHM.tif

echo "\nCompleted"

